<a href="https://colab.research.google.com/github/pyKi11er/deep_net_dev/blob/main/dnd26autumn_practice_week3_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Network Development, 2026 Autumn - Week 3 Practice - **Exercise sheet**

## Exercises

---

### Exercise 3.1: 1D temperature and rainfall time series

#### Problem Description

Two short time series are given in two arrays: the monthly average temperatures (`temperatures`) in Celsius and the average total monthly rainfall (`rainfall`) in millimeters for the twelve months of the year for Almaty, Kazakhstan.

Provide a solution for the questions below using NumPy as efficiently as possible!

(**Note:** The test cases provided are not exhaustive. They only check result correctness for the given example series.)

In [2]:
import numpy as np

temperatures = np.array([-4.6, -2.4, 4.5, 12.1, 17.1, 22.1, 24.4, 23.3, 18.0, 10.6, 2.9, -2.7], dtype=np.float32)
rainfall = np.array([34.7, 42.6, 72.4, 112.4, 98.7, 59.0, 42.9, 33.5, 27.8, 49.8, 55.3, 44.3], dtype=np.float32)


#### Question 1: Total Rainfall
Compute the total rainfall of the year and assign it to the `total_rainfall` variable.

In [3]:
# Implement your solution below


total_rainfall = np.sum(rainfall)

# Test case
assert np.isclose(total_rainfall, 673.4)
print("Question 1 passed! ")

Question 1 passed! 


#### Question 2: Maximum Temperature
Get the maximum temperature recorded during the year and assign it to the `max_temp` variable.

In [4]:
# Implement your solution below

max_temp = np.max(temperatures)


# Test case
assert np.isclose(max_temp, 24.4)
print("Question 2 passed! ")

Question 2 passed! 


#### Question 3: De Martonne Aridity Index
Compute the De Martonne Aridity Index $I = \frac{12 \times R}{T + 10}$ for each month. The result should be a 1D array of shape `(12,)` assigned to the `aridity_index` variable.

In [5]:
# Implement your solution below
aridity_index = (12 * rainfall) / (temperatures + 10)



# Test case
expected_aridity = np.array([77.11111111, 67.26315789, 59.91724138, 61.03167421, 43.70479705, 22.05607477, 14.96511628, 12.07207207, 11.91428571, 29.00970874, 51.44186047, 72.82191781])
assert np.allclose(aridity_index, expected_aridity)
print("Question 3 passed! ")

Question 3 passed! 


#### Question 4: Temperature Comparison (May vs September)
Check whether the temperature is higher in May than in September. The result should be a boolean assigned to the `may_gt_sep` variable (True if the temperature is higher in May).

In [9]:
# Implement your solution below


may_gt_sep = (temperatures[4] - temperatures[8]) > 0

# Test case
assert may_gt_sep == False
print("Question 4 passed! ")

Question 4 passed! 


#### Question 5: Coldest Month
Find the number of the coldest month of the year. The result should be an integer between 1 and 12 assigned to the `coldest_month` variable.

In [8]:
# Implement your solution below

coldest_month = np.argmin(temperatures) + 1


# Test case
assert coldest_month == 1
print("Question 5 passed! ")

Question 5 passed! 


#### Question 6: Rainiest Spring Month
Find the number of the rainiest month in spring. The result should be an integer (March: 3, April: 4, May: 5) assigned to the `rainiest_spring_month` variable.

In [20]:
# Implement your solution below


rainiest_spring_month = np.argmax(rainfall[2:5]) + 3
# Test case
assert rainiest_spring_month == 4
print("Question 6 passed! ")

[ 72.4 112.4  98.7]
[ 72.4 112.4  98.7]
4
Question 6 passed! 


**Solve the same exercise with the following constraint:** Do not use any literals (e.g., hard coded number, list, array constants like `1` or `2`) in your code (besides those, that are already provided)!

**Hint:** `np.arange()`, Slicing

In [22]:

START_IDX_OF_SPRING = 2
END_IDX_OF_SPRING = 5         # exclusive

MONTH_NUMBER_START = 1        # e.g., January is 1, not 0

# Implement your solution below

rainiest_spring_month = np.argmax(rainfall[np.arange(MONTH_NUMBER_START, END_IDX_OF_SPRING)]) + START_IDX_OF_SPRING



# Test case
assert rainiest_spring_month == 4
print("Question 6 passed! ")

Question 6 passed! 


#### Question 7: Autumn Mean Temperature
Compute the mean temperature during autumn months (September, October, November) and assign it to the `autumn_mean_temp` variable.

In [23]:
# Implement your solution below


autumn_mean_temp = np.mean(temperatures[8:11])

# Test case
assert np.isclose(autumn_mean_temp, 10.5)
print("Question 7 passed! ")

Question 7 passed! 


#### Question 8: Rain Comparison (Odd vs Even Months)
Determine if odd months (Jan, Mar, ...) had more total rain than even months (Feb, Apr, ...). The result should be a boolean (True if odd months had more total rainfall) assigned to the `more_odd_rain` variable.

In [25]:
# Implement your solution below

more_odd_rain = np.sum(rainfall[np.arange(0,12,2)]) > np.sum(rainfall[np.arange(1,12,2)])


# Test case
assert more_odd_rain == False
print("Question 8 passed! ")

Question 8 passed! 


#### Question 9: Maximum Winter Temperature
Get the maximum temperature during winter months (December, January, February). The result should be a floating point value assigned to the `max_winter_temp` variable.

**Constraint:** Handle the three months together in the same operations!

In [29]:
# Implement your solution below

max_winter_temp = np.max(temperatures[[0,1,11]])


# Test case
assert np.isclose(max_winter_temp, -2.4)
print("Question 9 passed! ")

Question 9 passed! 


#### Question 10: Mean Absolute Deviation of Temperature
Compute the average of the absolute differences between the monthly temperatures and the average of the twelve monthly temperatures. The result should be a floating point value assigned to the `temp_mad` variable.

In [30]:
# Implement your solution below

avg = np.average(temperatures)
temp_mad = np.average(abs(temperatures - avg))

# Test case
assert np.isclose(temp_mad, 9.084722)
print("Question 10 passed! ")

Question 10 passed! 


#### Question 11: Fahrenheit vs Celsius Difference
Check if any monthly temperatures have a difference less than 50 between its Fahrenheit and Celsius values ($T_F = 1.8 \times T_C + 32$). The result should be a boolean value assigned to the `has_diff_lt_50` variable.

In [33]:
# Implement your solution below
fahrenheit = temperatures * 1.8 + 32
has_diff_lt_50 = np.any(abs(temperatures - fahrenheit) < 50)

# Test case
assert has_diff_lt_50 == True
print("Question 11 passed! ")

Question 11 passed! 


#### Question 12: Total Rainfall in Sub-Zero Months
Compute total rainfall in months with negative temperatures. The result should be a floating point value assigned to the `subzero_rain` variable.

In [34]:
# Implement your solution below

subzero_rain = np.sum(rainfall[temperatures < 0])


# Test case
assert np.isclose(subzero_rain, 121.6)
print("Question 12 passed! ")

Question 12 passed! 


#### Question 13: Max Temperature of Rainy Autumn Months
Get the maximum temperature of autumn months (Sep, Oct, Nov) where rainfall exceeded 50mm. The result should be a floating point value assigned to the `max_rainy_autumn_temp` variable.

In [70]:
# Implement your solution below

autumn_months_mask = (np.arange(len(temperatures)) >= 8) & (np.arange(len(temperatures)) <= 10)

rainfall_gt_50_mask = rainfall > 50

combined_mask = autumn_months_mask & rainfall_gt_50_mask

# Get the maximum temperature from the months that satisfy the combined condition
max_rainy_autumn_temp = np.max(temperatures[combined_mask])

# Test case
assert np.isclose(max_rainy_autumn_temp, 2.9)
print("Question 13 passed! ")

Question 13 passed! 


**Try to find another approach!**

**Hints:**
- **Approach 1:** Get autumn temperatures and rainfalls separately by slicing. Then, get the maximum of autumn temperatures where the autumn rainfalls is greater than 50.
- **Approach 2:** Create a mask that identifies autumn months. You can find the maximum of the temperatures of those months where the autumn mask AND the "rainfall is greater than 50" mask are both True.

In [ ]:
# Implement your solution below




# Test case
assert np.isclose(max_rainy_autumn_temp, 2.9)
print("Question 13 passed! ")

#### Question 14: Months Above Series Mean
Get those month numbers where either the rainfall OR the temperature is above the annual average of its series. The result should be an array containing month numbers (January: 1, February: 2, ...). Assign it to the `above_avg_months` variable.

In [87]:
# Implement your solution below
avg_rain = np.average(rainfall)
avg_temp = np.average(temperatures)
gt_avg_rain = rainfall > avg_rain
gt_avg_temp = temperatures > avg_temp
mask =  gt_avg_rain | gt_avg_temp
print(np.where(mask)[0])
above_avg_months = np.where(mask)[0] + 1


# Test case
assert np.array_equal(above_avg_months, np.array([3, 4, 5, 6, 7, 8, 9, 10]))
print("Question 14 passed! ")

[2 3 4 5 6 7 8 9]
Question 14 passed! 


#### Question 15: Months where the Month number < Temperature

Get those month numbers where the month number (January: 1, February: 2, ...) is smaller than the temeprature value of the same month. The result should be an array containing month numbers. Assign it to the `index_lt_temp_months` variable.


In [ ]:
# Implement your solution below




# Test case
assert np.array_equal(index_lt_temp_months, np.array([3, 4, 5, 6, 7, 8, 9, 10]))
print("Question 15 passed! ")

#### Question 16: A Month with Above-Median Temp and Below-Median Rain
Get the number (January: 1, February: 2, ...) of **one of** those months where temperature is above the median temperature AND rainfall is below the median rainfall. The result should be an integer containing a month number IF there is such a month. Otherwise the result should be `None`. Assign the result to the `selected_month` variable.

In [ ]:
# Implement your solution below




# Test case
assert selected_month in [7, 8, 9]
print("Question 16 passed! ")

#### Question 17: Any Month where Temperature Greater than Rainfall
Find out whether the temperature value is greater than its corresponding rainfall value in any of the months. The result should be a boolean value assigned to the `temp_gt_rainfall` variable.

In [ ]:
# Implement your solution below




# Test case
assert temp_gt_rainfall == False
print("Question 17 passed! ")

#### Question 18: All Rainfall Values Greater than Max Temperature
Find out whether the rainfall values are all greater than the maximum temperature value of the year. The result should be a boolean value assigned to the `all_rainfall_gt_maxtemp` variable.

In [ ]:
# Implement your solution below




# Test case
assert all_rainfall_gt_maxtemp == True
print("Question 18 passed! ")

#### Question 19: Count Months with Rain Below Half Max Rain
Count in how many months the rainfall value is less than half of the maximum monthly rainfall. The result should be an integer value assigned to the `count_half_max_rain` variable.

In [ ]:
# Implement your solution below




# Test case
assert count_half_max_rain == 8
print("Question 19 passed! ")

#### Question 20: Warmest Winter Month
Get the month number of the warmest winter month (December: 12, January: 1, February: 2). The result should be an integer value assigned to the `warmest_winter_month` variable.

**Constraint:** Handle the three months together in the same operations!


In [ ]:
# Implement your solution below




# Test cases
assert warmest_winter_month == 2
print("Question 20 passed! ")

**Try to find another approach!**

**Hints:**
- **Approach 1:** Index into the array of winter month numbers with the index of warmest month only taken across winter months.
- **Approach 2:** Overwrite temperatures of non-winter months with a really small number (e.g., negative infinity), then find the month with the maximum temeprature. Make sure to not modify the original temperatures array, but create a copy instead first (e.g., using `np.ndarray.copy()`).

In [ ]:
# Implement your solution below




# Test cases
assert warmest_winter_month == 2
print("Question 20 passed! ")